apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bibliotekdk-files-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: cephfs
