<?php
/**
 * @file
 * Code for Bibliotek.dk Autocomplete behaviour
 */


/**
 * Implements hook_menu().
 */
function bibdk_autocomplete_behaviour_menu() {
  $items['bibdk/behaviour/autocomplete'] = array(
    'title' => 'Bibliotek.dk autocomplete behaviour',
    'description' => 'Autocomplete behaviour callback',
    'page callback' => 'bibdk_autocomplete_behaviour_callback',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_form_FORM_ID_alter() for form search_block_form.
 */
function bibdk_autocomplete_behaviour_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $form['#attached']['js'][] = drupal_get_path('module', 'bibdk_autocomplete_behaviour') . '/js/bibdk_autocomplete_behaviour.js';
  return $form;
}


/**
 * Callback for autocomplete behaviour.
 */
function bibdk_autocomplete_behaviour_callback($json_data) {
  $behaviour_data = $_POST;
  $settings = variable_get('bibdk_autocomplete_var', array());
  foreach ($behaviour_data['behaviour'] as $key => $fields) {
    if (!isset($fields['suggestions'])) {
      unset($behaviour_data['behaviour'][$key]);
      continue;
    }
    $p_uuid = $fields['pageUuid'];
    $i_uuid = $fields['inputUuid'];
    $type = $settings[$p_uuid]['vars'][$i_uuid]['type'];
    $behaviour_data['behaviour'][$key]['type'] = $type;
    unset($behaviour_data['behaviour'][$key]['id']);
  }
  bibdk_behaviour_log($behaviour_data);
}
