<?php

/**
 * @file
 * Webservice mockup of Open Agency
 */
function bibdk_borchk_webservice_mockup_menu() {
  $items['bibdk_borchk_webservice'] = array(
    'page callback' => 'bibdk_borchk_webservice_mockup_request',
    'access callback' => 'bibdk_borchk_webservice_mockup_access',
  );
  $items['bibdk_borchk_webservice/test'] = array(
    'page callback' => 'bibdk_borchk_webservice_test',
    'access callback' => TRUE
  );

  return $items;
}

function bibdk_borchk_webservice_test() {
  return '<form name="test" action="bibdk_borchk_webservice" method="POST" target="_blank"><textarea name="xml"></textarea><input type="submit" name="sub" value="submit"/></form>';
}


/**
 * Faking the request and returns result. If other requests are made than on city = københavn an error will be returned.
 * @return String json
 */
function bibdk_borchk_webservice_mockup_request() {
   if (isset($_POST['xml'])) {
    $data = rawurldecode($_POST['xml']);
  }
  else {
    $data = file_get_contents('php://input');
  }
  $path = drupal_get_path('module', 'bibdk_borchk_webservice_mockup');
  if( $data ) {
    $envelope = bibdk_borchk_webservice_mockup_parse_xml($data);
  }
  else {
    echo 'welcome to bibdk_borchk_webservice mockup';
    return;
  }

  $request = $envelope->Body->children()->borrowerCheckRequest;
  // good user
  $gooduser = ( $request->serviceRequester == 'bibliotek.dk' &&
              $request->libraryCode == 'DK-872920' &&
              $request->userId == '0019' &&
              $request->userPincode == '0019');
  drupal_add_http_header('Content-Type', 'application/json');
  if( $gooduser ) {
    $resp = file_get_contents($path.'/gooduser.json');
  }
  else{
    $resp = file_get_contents($path.'/baduser.json');
  }
  print $resp;
}

/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function bibdk_borchk_webservice_mockup_parse_xml($soap){
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function bibdk_borchk_webservice_mockup_access() {
  return TRUE;
}
