<?php
/**
 * @file
 * Drupal functions for sbkopi
 */

/** load field hooks * */
include_once 'includes/bibdk_sbkopi.ajax.inc';

/**
 * Implements hook_ting_client_webservice().
 *
 * @see ting_client.module
 */
function bibdk_sbkopi_ting_client_webservice() {
  $ret = array();
  $ret['statsbib']['class'] = 'bibdk_statsbib';
  $ret['statsbib']['url'] = 'bibdk_statsbib_url';

  $ret['statsbibjournal']['class'] = 'bibdk_sb_journal';
  $ret['statsbibjournal']['url'] = 'bibdk_statsbibjournal_url';

  $ret['statsbibsubscriber']['class'] = 'bibdk_sb_subscriber';
  $ret['statsbibsubscriber']['url'] = 'bibdk_statsbibsubscriber_url';

  return $ret;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add 2 fields to webservice client settings
 *
 * @url to borchk
 * @servicerequester
 * */
function bibdk_sbkopi_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['sbkopi'] = array(
    '#type' => 'fieldset',
    '#title' => t('SB Copy Settings'),
    '#descriptions' => t('Settings for SB copy service'),
  );
  $form['sbkopi']['bibdk_sbkopi_place_copy_request_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL to SB copy service'),
    '#description' => t('URL to statsbibliotekets place copy service e.g., https://webservice.statsbiblioteket.dk/placeCopyRequest'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_sbkopi_place_copy_request_url', FALSE),
  );
  $form['sbkopi']['bibdk_sbkopi_request_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Service username'),
    '#description' => t('User for authentication on service'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_sbkopi_request_user', FALSE),
  );
  $form['sbkopi']['bibdk_sbkopi_request_pass'] = array(
    '#type' => 'textfield',
    '#title' => t('Service password'),
    '#description' => t('Password for authentication on service'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_sbkopi_request_pass', FALSE),
  );
  $form['sbkopi']['hr'] = array(
    '#markup' => '<hr />'
  );
  $form['sbkopi']['bibdk_sbkopi_journal_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Url to SB Journal service'),
    '#description' => t('Url to statsbibliotekets journal service e.g., https://webservice.statsbiblioteket.dk/copydanws/journal'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_sbkopi_journal_url', FALSE),
  );
  $form['sbkopi']['bibdk_sbkopi_subscriber_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Url to SB Subscriber service'),
    '#description' => t('Url to statsbibliotekets subscriber service e.g., https://webservice.statsbiblioteket.dk/copydanws/subscriber'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_sbkopi_subscriber_url', FALSE),
  );
}

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function bibdk_sbkopi_menu() {
  $items['sbkopi/ajax'] = array(
    'page callback' => 'bibdk_sbkopi_ajax_get_options',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/bibdk_sbkopi.ajax.inc',
  );

  $items['reservation/sbkopi/%'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_sbkopi_reservation_form', 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/bibdk_sbkopi.reservation.inc',
  );
  $items['reservation/sbkopi/receipt/%'] = array(
    'page callback' => 'bibdk_sbkopi_reservation_receipt',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/bibdk_sbkopi.reservation.inc',
  );

  return $items;
}

/**
 * implements hook_theme().
 */
function bibdk_sbkopi_theme() {
  $items = array();
  $items['bibdk_sbkopi_button'] = array(
    'variables' => array(
      'link' => array(),
      'helptext' => '',
      'pid' => '',
    ),
    'template' => 'theme/bibdk-sbkopi-button',
  );

  return $items;
}

/**
 * Implements hook_ting_openformat_actions().
 */
function bibdk_sbkopi_ting_openformat_actions($type, $entity, $view_mode, $langcode) {
  if ($type == 'bibdkManifestation') {
    // Check for sb link for following types
    $sb_type_list = array('Tidsskriftsartikel', 'Tidsskrift', 'Årbog', 'Periodikum', );

    if (in_array($entity->getSubType(), $sb_type_list)) {
      drupal_add_js(drupal_get_path('module', 'bibdk_sbkopi') . '/js/ajaxGetCopyOptions.js');
      $actions['sbkopi'] = array(
        '#theme' => 'html_tag',
        '#tag' => 'span',
        '#value' => '',
        '#attributes' => array(
          'class' => 'bibdk-sb_kopi-replaceme',
          'pid' => $entity->id,
        ),
        '#weight' => 0.1,
      );

      return $actions;
    }
  }
}
