<?php

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function bibdk_forsrights_ting_client_webservice() {
  $ret = array();
  $ret['forsrights']['class'] = 'bibdk_forsrights';
  $ret['forsrights']['url'] = 'bibdk_forsrights_url';
  $ret['forsrights']['xsdNamespace'] = array(0=>'http://oss.dbc.dk/ns/forsrights');
  return $ret;
}

function bibdk_forsrights_get_library_list ($serviceName) {
  $xml = bibdk_forsrights_request($serviceName);
  return bibdk_forsrights_parse_response($xml);
}

function bibdk_forsrights_parse_response($xml){
  $ret = array();
  $dom = new DomDocument();
  if (!@$dom->loadXML($xml)) {
    if ( BibdkClient::$enable_logging ) {
      watchdog('bibdk_provider', t('BIBDK client could not load response: %xml', array('%xml' => var_export($xml, TRUE))), array(), WATCHDOG_ERROR);
    }
    return FALSE;
  }
  $xpath = new DomXPATH($dom);

  $query = '//fr:customer';
  $nodelist = $xpath->query($query);
  foreach ($nodelist as $node) {
    $ret[] = $node->nodeValue;
  }

  return $ret;
}

/**
 * do a request
 * */
function bibdk_forsrights_request($serviceName, $outputType = 'xml') {
  $client = new ting_client_class();
  // this is the real request
  $response = $client->do_request('forsrights', array('serviceName' => $serviceName,'outputType' => $outputType,));
  return $response;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add field to webservice client settings
 * @url to FORS Rights
 * */
function bibdk_forsrights_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['ting']['bibdk_forsrights_url'] = array(
    '#type' => 'textfield',
    '#title' => t('FORS Rights URL'),
    '#description' => t('URL to forsrights e.g. http://forsrights.addi.dk/1.0/'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_forsrights_url', FALSE),
  );
}

/**
 * @return Array
 */
function bibdk_forsrights_how_r_u() {
  return array('forsrights' => variable_get('bibdk_forsrights_url'));
}
