<?php
/**
 * @file
 * Bibliotek.dk search carousel module main file.
 */

/**
 * Implements hook_menu().
 */
function bibdk_search_carousel_menu() {

  $items = array();

  $items['bibdk_search_carousel/results/ajax'] = array(
    'title' => 'Show search carousel results',
    'page callback' => 'bibdk_search_carousel_result',
    'access arguments' => array('access content'),
    'file' => 'bibdk_search_carousel.ajax.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/user-interface/bibdk_search_carousel'] = array(
    'title' => 'Bibliotek.dk search carousel',
    'description' => 'Manage content for frontpage carousel.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_search_carousel_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'bibdk_search_carousel.admin.inc',
  );

  $items['admin/config/user-interface/bibdk_search_carousel/settings'] = array(
    'title' => 'Content',
    'description' => 'Manage content for frontpage carousel.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/config/user-interface/bibdk_search_carousel/frontend_settings'] = array(
    'title' => 'Frontend settings',
    'description' => 'Manage settings for the display of frontpage carousel',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_search_carousel_settings_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'bibdk_search_carousel.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['admin/config/user-interface/bibdk_search_carousel/search_settings'] = array(
    'title' => 'Search settings',
    'description' => 'Manage settings for the search webservice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_search_carousel_search_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'bibdk_search_carousel.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  return $items;

}



/**
 * Implements hook_help().
 */
function bibdk_search_carousel_help($path, $arg) {
  switch ($path) {
    case 'admin/help#bibdk_search_carousel';
      $file = drupal_get_path('module', 'bibdk_search_carousel') . "/help/bibdk_search_carousel.php";
      return $output = file_get_contents($file);
    break;
  }
}



/**
 * Implements hook_theme().
 */
function bibdk_search_carousel_theme($existing, $type, $theme, $path) {
  return array(
    'bibdk_search_carousel' => array(
      'variables' => array(
        'searches' => NULL,
        'tab_position' => NULL,
      ),
      'template' => 'templates/bibdk_search_carousel',
      'file' => 'bibdk_search_carousel.theme.inc',
    ),
    'bibdk_search_carousel_item' => array(
      'variables' => array(
        'image'   => NULL,
        'title'   => NULL,
        'creator' => NULL,
        'url'     => NULL,
      ),
      'template' => 'templates/bibdk_search_carousel_item',
      'file' => 'bibdk_search_carousel.theme.inc',
    ),
    'bibdk_search_carousel_admin_form' => array(
      'render element' => 'form',
    ),
  );
}



/**
 * Implements hook_ctools_plugin_directory().
 */
function bibdk_search_carousel_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}



/**
 * Returns the content for a search carousel tab. It utilizes cache to optimize the cover page search.
 * It will fill the cache based on the tab index provided. This index matches the search carousel
 * query index set in the administration backend, when defining the tabs.
 *
 * If no cache is found, it tries to search the data well repeatedly until
 * BIBDK_SEARCH_CAROUSEL_COVERS_MAX or BIBDK_SEARCH_CAROUSEL_QUERIES_MAX is reached. 
 * If data still do not exists, an empty string is returned.
 *
 * @param int $index
 *  Search carsousel tab index.
 *
 * @param array $bibdk_seach_queries
 *  query string and search delimiters.
 *
 * @return array
 *  Returns a render array or the empty array if no covers are found.
 */
function _bibdk_search_carousel_get_content($index = 0, $bibdk_seach_queries = array())  {

  global $language;
  
  if (empty($bibdk_seach_queries[$index]['query'])) {
    return array();
  }

  $cache_key = 'bibdk_search_carousel_content_' . $language->language . drupal_html_id(md5($bibdk_seach_queries[$index]['query'], TRUE));

  if ($cache = cache_get($cache_key, 'cache')) {
    return $cache->data;
  }

  $query = $bibdk_seach_queries[$index];

  // Give other modules an option to alter the carousel query
  // See: bibdk_search_carousel_bibdk_search_carousel_query() below
  $query = module_invoke_all('bibdk_search_carousel_query', $query);

  $cover_items = array();

  $max_covers = variable_get('bibdk_search_carousel_covers_max', 20);
  $max_queries = variable_get('bibdk_search_carousel_queries_max', 400);

  $num_results = 40;
  $start = 1;
  $more = TRUE;

  // Loop until we have $max_covers covers, or we've reached $max_queries queries.
  while ((count($cover_items) < $max_covers) && ($start - $num_results < $max_queries) && $more) {

    // If a query is defined, do a look-up else do nothing.
    if ($query) {

      $params['query'] = $query['query'];

      // results pr. page (opensearch::stepValue) ... in ting-client/lib/request/TingClientSearchRequest.php this is called numResults
      $params['numResults'] = $num_results;

      // page number (opensearch::start)
      $params['start'] = $start; // search results start at position 1

      $params['includeHoldingsCount'] = FALSE;

      // search profile (opensearch::profile)
      $params['profile'] = variable_get('ting_search_profile', FALSE);
      if (!($params['profile'])) {
        watchdog('ting search carousel', 'search profile is not set - yields no search results', array(), WATCHDOG_ERROR, url('admin/config/ting/settings'));
      }

      // agency (opensearch::agency)
      $params['agency'] = variable_get('ting_agency');
      if (!($params['agency'])) {
        watchdog('ting search carousel', 'agency is not set - yields no search results', array(), WATCHDOG_ERROR, url('admin/config/ting/settings'));
      }

      // set Object Format
      $params['objectFormat'] = variable_get('objectFormat', 'briefDisplay');

      if (isset($params['query']) && empty($params['query'])) {
        return array();
      }

      // do the actual search via ting_client_class
      $client = new ting_client_class();
      $ting_client_search_result = $client->do_request('search', $params);

      if (!$ting_client_search_result) {
        return array();
      }

      $more = (isset($result->more)) ? $result->more : FALSE;
    }

    $num_total_collections = $ting_client_search_result->numTotalCollections;

    // Loop over the search results collecting basic object information.
    foreach ($ting_client_search_result->collections as $ting_client_object_collection) {

      $manifestations = $ting_client_object_collection->getFormattedCollection()->getBriefDisplay()->manifestation;

      foreach ($manifestations as $manifestation) {


        $item = array();
        $item['pid'] = (!empty($manifestation->identifier->{'$'})) ? $manifestation->identifier->{'$'} : FALSE;

        if ($item['pid']) {
          $i = explode(':', $item['pid']);
          $item['lok'] = $i[0];
          $item['lid'] = $i[1];
        }

        if (!empty($item['lid'])) {
          $moreinfo_path = open_moreinfo_object_path($item['lid'], 'detailUrl');
          if (file_exists($moreinfo_path)) {
            // NB: don't check if image_style_url() create an image. Because it don't.
            $cover_url = image_style_url('medium', $moreinfo_path);
            $url = url(
              'search/work/',
              array(
                'query' => array('search_block_form' => 'rec.id='. $item['pid']),
                'fragment' => 'content',
                'html' => TRUE,
              )
            );
            $cover_items[] = array(
              '#theme'   => 'bibdk_search_carousel_item',
              '#image'   => $cover_url,
              '#title'   => (!empty($manifestation->title->{'$'})) ? $manifestation->title->{'$'} : NULL,
              '#creator' => (!empty($manifestation->creator->{'$'})) ? $manifestation->creator->{'$'} : NULL,
              '#url'     => $url,
            );
          }
        }
      }

    }

    // Count up search start position
    $start += $num_results;

  }

  if (!empty($cover_items)) {
    cache_set($cache_key, $cover_items, 'cache');
  }

  return $cover_items;

}


/**
 * Implements hook_bibdk_search_carousel_query().
 */
function bibdk_search_carousel_bibdk_search_carousel_query($query) {

  $bibdk_query_prefix = CQL_AND . variable_get('bibdk_search_carousel_week_search_code', 'dkcclterm.kk') . '=(';
  $bibdk_query_suffix = ')';
  $bibdk_dateformat = variable_get('bibdk_search_carousel_dateformat', 'bk\mYW');
  $today = time();
  $week = 7 * 24 * 60 * 60; // 7 days; 24 hours; 60 mins; 60secs

  $periods = array();
  for ($n = 0; $n < $query['period']; $n++) {
    $offset = $query['offset'];
    $weeks = $week * ( $n + $offset );
    $periods[] = date($bibdk_dateformat, $today - $weeks);
  }
  if ( !empty($periods)  ) {
    $query['query'] = $query['query'] . $bibdk_query_prefix . implode(CQL_OR, $periods) . $bibdk_query_suffix;
  }

  return $query;
}
