<?php
define("OGP_SITE_URL", "https://bibliotek.dk");

/**
 * Implements hook_html_head_alter.
 * Add ogp metadata in page headers
 * @param $head_elements
 */
function bibdk_ogp_metadata_html_head_alter(&$head_elements){
  $path = $_GET['q'];
  $switch = 'frontpage';
  if(strpos($path, 'search') !== -1){
    $switch = 'search';
  }

  switch($switch){
    case 'search':
      $url = url(current_path(), array('absolute' => TRUE,'query' => drupal_get_query_parameters()));
      bibdk_ogp_metadata_all_head($head_elements, 'search bibliotek.dk', $url);
      break;
    default:
      bibdk_ogp_metadata_all_head($head_elements);
      break;
  }
  // @TODO add more specific pages - eg. work
}

/**
 * Generel headers
 * add elements required : title, type, image, url
 * @param $head_elements
 * @param $title
 * @param $url
 */
function bibdk_ogp_metadata_all_head(&$head_elements, $title = 'bibliotek.dk', $url = "OGP_SITE_URL"){
  //type - always website
  $head_elements['ogp_type']= array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'property'=>'og:type',
      'content' => 'website'
    )
  );
  drupal_add_html_head($head_elements, 'ogp_type');
  // title - from parameters
  $head_elements['ogp_title']= array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'property'=>'og:title',
      'content' => $title,
    )
  );
  drupal_add_html_head($head_elements, 'ogp_title');
  // image - use logo for now - remove language prefix
  $image_url = url('/profiles/bibdk/themes/bibdk_theme/img/dbc-logo-footer-nopayoff.png', array('absolute'=>TRUE, 'language'=>''));
  $head_elements['ogp_image']= array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'property'=>'og:image',
      'content' => $image_url,
    )
  );
  drupal_add_html_head($head_elements, 'ogp_image');
  // url
  $head_elements['ogp_url']= array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array(
      'property'=>'og:url',
      'content' => $url,
    )
  );
  drupal_add_html_head($head_elements, 'ogp_url');
}


