<?php
/**
 * @file
 * bibdk_example_content_articles.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function bibdk_example_content_articles_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'3\',
      \'uid\' => \'0\',
      \'title\' => \'FILM\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'d7533b1e-ab30-4016-a515-172244699006\',
      \'nid\' => \'3\',
      \'type\' => \'bibdk_article\',
      \'language\' => \'und\',
      \'created\' => \'1421056125\',
      \'changed\' => \'1421056234\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'ba806a21-2a8b-416e-a901-2ee8ea8ee18c\',
      \'revision_timestamp\' => \'1421056234\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Film er en samling billeder der bliver vist så hurtigt at det skaber en illusion af bevægelse. Ofte er billederne kombineret med lyd\',
            \'summary\' => \'\',
            \'format\' => \'html_5\',
          ),
        ),
      ),
      \'field_weight\' => array(),
      \'field_link\' => array(
        \'und\' => array(
          array(
            \'value\' => \'http://en.wikipedia.org/wiki/Film\',
            \'format\' => NULL,
            \'safe_value\' => \'http://en.wikipedia.org/wiki/Film\',
          ),
        ),
      ),
      \'field_column\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'11\',
          ),
        ),
      ),
      \'field_image\' => array(),
      \'field_link_classes\' => array(),
      \'field_link_text\' => array(
        \'und\' => array(
          array(
            \'value\' => \'FILM\',
            \'format\' => NULL,
            \'safe_value\' => \'FILM\',
          ),
        ),
      ),
      \'field_page_region\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'10\',
          ),
        ),
      ),
      \'field_page_type\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'5\',
          ),
        ),
      ),
      \'field_rows\' => array(
        \'und\' => array(
          array(
            \'value\' => \'3\',
          ),
        ),
      ),
      \'name\' => \'\',
      \'picture\' => \'0\',
      \'data\' => NULL,
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'4\',
      \'uid\' => \'0\',
      \'title\' => \'BOG\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'300ef634-e679-467d-b110-b7c600936a5a\',
      \'nid\' => \'4\',
      \'type\' => \'bibdk_article\',
      \'language\' => \'und\',
      \'created\' => \'1421056125\',
      \'changed\' => \'1421056265\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'273c50d5-6922-4691-babc-a850ffa6c410\',
      \'revision_timestamp\' => \'1421056265\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'A book is a set of written, printed, illustrated, or blank sheets, made of ink, paper, parchment, or other materials, usually fastened together to hinge at one side. A single sheet within a book is called a leaf, and each side of a leaf is called a page. A set of text-filled or illustrated pages produced in electronic format is known as an electronic book, or e-book.\',
            \'summary\' => \'\',
            \'format\' => \'html_5\',
          ),
        ),
      ),
      \'field_weight\' => array(),
      \'field_link\' => array(
        \'und\' => array(
          array(
            \'value\' => \'http://en.wikipedia.org/wiki/bog\',
            \'format\' => NULL,
            \'safe_value\' => \'http://en.wikipedia.org/wiki/bog\',
          ),
        ),
      ),
      \'field_column\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'11\',
          ),
        ),
      ),
      \'field_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'6\',
            \'uid\' => \'1\',
            \'filename\' => \'166a4f497e247390af921d998588844d.jpg\',
            \'uri\' => \'public://ting_search_carousel/166a4f497e247390af921d998588844d.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'32799\',
            \'status\' => \'1\',
            \'timestamp\' => \'1420808062\',
            \'uuid\' => \'580495fc-c581-409d-9fae-fb58cbec4413\',
            \'alt\' => \'\',
            \'title\' => \'\',
            \'width\' => \'77\',
            \'height\' => \'68\',
          ),
        ),
      ),
      \'field_link_classes\' => array(),
      \'field_link_text\' => array(
        \'und\' => array(
          array(
            \'value\' => \'mere om bøger\',
            \'format\' => NULL,
            \'safe_value\' => \'mere om bøger\',
          ),
        ),
      ),
      \'field_page_region\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'9\',
          ),
        ),
      ),
      \'field_page_type\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'3\',
          ),
        ),
      ),
      \'field_rows\' => array(),
      \'name\' => \'\',
      \'picture\' => \'0\',
      \'data\' => NULL,
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'5\',
      \'uid\' => \'0\',
      \'title\' => \'ALLE MATERIALER\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'0e39bb45-8469-454a-ad96-22830a52e70c\',
      \'nid\' => \'5\',
      \'type\' => \'bibdk_article\',
      \'language\' => \'und\',
      \'created\' => \'1421056125\',
      \'changed\' => \'1421056328\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'b3d7e4ea-8d9b-4a61-9a6b-5269954a4b6a\',
      \'revision_timestamp\' => \'1421056328\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "Hesten (latin: Equus caballus) er et hovbærende pattedyr.\\r\\n\\r\\nDen er tågænger, dvs. den går på spidsen af tæerne, og heste har på hver fod kun en enkelt tå, der svarer til menneskets langefinger og midterste tå. Tåens negl danner en hov, som hesten går på, men på blød jord kan den også hvile på tåspidsen lige efter hoven.",
            \'summary\' => \'\',
            \'format\' => \'html_5\',
          ),
        ),
      ),
      \'field_weight\' => array(),
      \'field_link\' => array(
        \'und\' => array(
          array(
            \'value\' => \'http://en.wikipedia.org/wiki/hest\',
            \'format\' => NULL,
            \'safe_value\' => \'http://en.wikipedia.org/wiki/hest\',
          ),
        ),
      ),
      \'field_column\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'12\',
          ),
        ),
      ),
      \'field_image\' => array(),
      \'field_link_classes\' => array(),
      \'field_link_text\' => array(
        \'und\' => array(
          array(
            \'value\' => \'wikihest\',
            \'format\' => NULL,
            \'safe_value\' => \'wikihest\',
          ),
        ),
      ),
      \'field_page_region\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'10\',
          ),
        ),
      ),
      \'field_page_type\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'8\',
          ),
        ),
      ),
      \'field_rows\' => array(
        \'und\' => array(
          array(
            \'value\' => \'3\',
          ),
        ),
      ),
      \'name\' => \'\',
      \'picture\' => \'0\',
      \'data\' => NULL,
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'6\',
      \'uid\' => \'0\',
      \'title\' => \'MUSIK\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'12289319-9963-46bf-8314-4420feed64bf\',
      \'nid\' => \'6\',
      \'type\' => \'bibdk_article\',
      \'language\' => \'und\',
      \'created\' => \'1421056125\',
      \'changed\' => \'1421056347\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'3fc085b4-74e4-4b9e-9468-8ee32e12b143\',
      \'revision_timestamp\' => \'1421056347\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Musik opfattes traditionelt som en sammensætning af toner, der synges eller spilles på et instrument. En tænketank i USA definerede musik som "mønstre af lyde, der varierer i højde og varighed og som frembringes af følelsesmæssige, sociale, kulturelle og intellektuelle grunde". Den bredeste definition er at musik er organiserede lydbegivenheder der opfattes æstetisk\',
            \'summary\' => \'\',
            \'format\' => \'html_5\',
          ),
        ),
      ),
      \'field_weight\' => array(),
      \'field_link\' => array(
        \'und\' => array(
          array(
            \'value\' => \'http://en.wikipedia.org/wiki/musilk\',
            \'format\' => NULL,
            \'safe_value\' => \'http://en.wikipedia.org/wiki/musilk\',
          ),
        ),
      ),
      \'field_column\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'12\',
          ),
        ),
      ),
      \'field_image\' => array(),
      \'field_link_classes\' => array(),
      \'field_link_text\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Musik\',
            \'format\' => NULL,
            \'safe_value\' => \'Musik\',
          ),
        ),
      ),
      \'field_page_region\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'10\',
          ),
        ),
      ),
      \'field_page_type\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'6\',
          ),
        ),
      ),
      \'field_rows\' => array(
        \'und\' => array(
          array(
            \'value\' => \'4\',
          ),
        ),
      ),
      \'name\' => \'\',
      \'picture\' => \'0\',
      \'data\' => NULL,
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
