<?php
/**
 * @file
 * Bibliotek.dk search carousel module main file.
 */

/**
 * Implements hook_menu().
 */
function bibdk_search_carousel_menu() {
  $items = array();
  $items['admin/config/ting/ting_search_carousel/bibdk_settings'] = array(
    'title' => 'Bibliotek.dk settings',
    'description' => 'Manage Bibliotek.dk settings for the search webservice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_search_carousel_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'bibdk_search_carousel.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );
  return $items;
}


/**
 * Implements hook_help().
 */
function bibdk_search_carousel_help($path, $arg) {
  switch ($path) {
    case 'admin/help#bibdk_search_carousel';
      $file = drupal_get_path('module', 'bibdk_search_carousel') . "/help/bibdk_search_carousel.php";
      return $output = file_get_contents($file);
    break;
  }
}


/**
 * Implements hook_form_id_alter().
 */
function bibdk_search_carousel_form_ting_search_carousel_admin_form_alter(&$form, &$form_state, $form_id) {

  drupal_add_css(drupal_get_path('module', 'bibdk_search_carousel') . '/bibdk_search_carousel.css');

  // Get current saved queries.
  $searches = variable_get('ting_carousel_search_queries', array());

  $period = array(
    '#title' => t('Period', array(), array('context' => 'bibdk_search_carousel')),
    '#type' => 'select',
    '#options' => array(
      0 => t('All', array(), array('context' => 'bibdk_search_carousel')),
      1 => t('1 week', array(), array('context' => 'bibdk_search_carousel')),
      2 => t('@n weeks', array('@n' => '2'), array('context' => 'bibdk_search_carousel')),
      3 => t('@n weeks', array('@n' => '3'), array('context' => 'bibdk_search_carousel')),
      4 => t('@n weeks', array('@n' => '4'), array('context' => 'bibdk_search_carousel')),
      5 => t('@n weeks', array('@n' => '5'), array('context' => 'bibdk_search_carousel')),
      6 => t('@n weeks', array('@n' => '6'), array('context' => 'bibdk_search_carousel')),
      7 => t('@n weeks', array('@n' => '7'), array('context' => 'bibdk_search_carousel')),
      8 => t('@n weeks', array('@n' => '8'), array('context' => 'bibdk_search_carousel')),
      9 => t('@n weeks', array('@n' => '9'), array('context' => 'bibdk_search_carousel')),
      10 => t('@n weeks', array('@n' => '10'), array('context' => 'bibdk_search_carousel')),
      11 => t('@n weeks', array('@n' => '11'), array('context' => 'bibdk_search_carousel')),
      12 => t('@n weeks', array('@n' => '12'), array('context' => 'bibdk_search_carousel')),
    ),
    '#default_value' => isset($item['period']) ? $item['period'] : '',
    '#description' => t('Select period for this carousel search.', array(), array('context' => 'bibdk_search_carousel')),
  );

  $offset = array(
    '#title' => t('Offset', array(), array('context' => 'bibdk_search_carousel')),
    '#type' => 'select',
    '#options' => array(
      0 => t('None', array(), array('context' => 'bibdk_search_carousel')),
      1 => t('1 week', array(), array('context' => 'bibdk_search_carousel')),
      2 => t('@n weeks', array('@n' => '2'), array('context' => 'bibdk_search_carousel')),
      3 => t('@n weeks', array('@n' => '3'), array('context' => 'bibdk_search_carousel')),
      4 => t('@n weeks', array('@n' => '4'), array('context' => 'bibdk_search_carousel')),
      5 => t('@n weeks', array('@n' => '5'), array('context' => 'bibdk_search_carousel')),
      6 => t('@n weeks', array('@n' => '6'), array('context' => 'bibdk_search_carousel')),
      7 => t('@n weeks', array('@n' => '7'), array('context' => 'bibdk_search_carousel')),
      8 => t('@n weeks', array('@n' => '8'), array('context' => 'bibdk_search_carousel')),
      9 => t('@n weeks', array('@n' => '9'), array('context' => 'bibdk_search_carousel')),
      10 => t('@n weeks', array('@n' => '10'), array('context' => 'bibdk_search_carousel')),
      11 => t('@n weeks', array('@n' => '11'), array('context' => 'bibdk_search_carousel')),
      12 => t('@n weeks', array('@n' => '12'), array('context' => 'bibdk_search_carousel')),
    ),
    '#default_value' => isset($item['offset']) ? $item['offset'] : '',
    '#description' => t('Select offset for this carousel search.', array(), array('context' => 'bibdk_search_carousel')),
  );

  $searches_num = sizeof($form['ting_search_carousel']['ting_searches']);
  for ($i = 0; $i < $searches_num; $i++) {
    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel'] = array(
      '#type' => 'fieldset',
      '#title' => t('Search settings', array(), array('context' => 'bibdk_search_carousel')),
      '#title_display' => 'invisible',
    );
    $period['#default_value']    = isset($searches[$i]['period'])    ? $searches[$i]['period']    : '';
    $offset['#default_value']    = isset($searches[$i]['offset'])    ? $searches[$i]['offset']    : '';

    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel']['period[]'] = $period;
    $form['ting_search_carousel']['ting_searches']['search_' . $i]['bibdk_search_carousel']['offset[]'] = $offset;

    $form['ting_search_carousel']['ting_searches']['search_' . $i]['remove[]']['#suffix'] = '';
  }

  // Custom form submit handler.
  $form['#submit'] = array('bibdk_search_carousel_search_submit');

}


/**
 * Submit handler for admin backend queries form.
 *
 * @param $form
 *   Form.
 * @param $form_state
 *   Form state.
 */
function bibdk_search_carousel_search_submit($form, &$form_state) {
  $c = count($form_state['input']['title']);
  $searches = array();
  $search_items = array();

  $hidden = variable_get('ting_carousel_search_queries_hidden', array());

  for ($i = 0; $i < $c; $i++) {
    if ( !in_array($i, $hidden) ) {
      // Make an array for saving, ignoring queries w/o title.
      if ( !empty($form_state['input']['title'][$i]) ) {
        $searches[] = array(
          'title' => $form_state['input']['title'][$i],
          'subtitle' => $form_state['input']['subtitle'][$i],
          'query' => $form_state['input']['query'][$i],
          'period' => $form_state['input']['period'][$i],
          'offset' => $form_state['input']['offset'][$i]
        );
      }
    }
  }

  /**
   * @TODO: Add clear cache button and detect changes in the query input fields
   * so only partial cache can be rebuild. This will slow down the submit but
   * may speed up the presentation for the users by kick starting the cache.
   */

  // Save the queries as a persistent variable.
  variable_set('ting_carousel_search_queries', $searches);

  // Clear carousel search cache
  cache_clear_all('ting_search_carousel_result', 'cache');
}


/**
 * Implements hook_ting_search_carousel_query().
 */
function bibdk_search_carousel_ting_search_carousel_query($query) {

  $bibdk_query_prefix = CQL_AND . variable_get('bibdk_search_carousel_week_search_code', 'dkcclterm.kk') . '=(';
  $bibdk_query_suffix = ')';
  $bibdk_dateformat = variable_get('bibdk_search_carousel_dateformat', 'bk\mYW');
  $today = time();
  $week = 7 * 24 * 60 * 60; // 7 days; 24 hours; 60 mins; 60secs

  $periods = array();
  for ($n = 0; $n < $query['period']; $n++) {
    $offset = $query['offset'];
    $weeks = $week * ( $n + $offset );
    $periods[] = date($bibdk_dateformat, $today - $weeks);
  }
  if ( !empty($periods)  ) {
    $query['query'] = $query['query'] . $bibdk_query_prefix . implode(CQL_OR, $periods) . $bibdk_query_suffix;
  }

  return $query;
}
