#! groovy
def NAMESPACE = 'frontend-features'
def DEPLOYS
def GITREPOS

pipeline {
  agent {
    node { label 'master' }
  }
  options {
    buildDiscarder(logRotator(artifactDaysToKeepStr: "", artifactNumToKeepStr: "", daysToKeepStr: "", numToKeepStr: "5"))
    timestamps()
    gitLabConnection('gitlab.dbc.dk')
    // Limit concurrent builds to one pr. branch.
    disableConcurrentBuilds()
  }
  stages {
    stage('get config'){
      agent {
        node { label 'master' }
      }
      steps{
        dir('bibdk_config'){
          git branch: 'develop',
            credentialsId: 'jenkins (dscrum-is SSH key)',
            url: 'gitlab.dbc.dk:d-scrum/d7/bibliotek-dk/bibdk_config.git'
          stash name: "kube-config", includes: "jenkins/kubeconfig.yaml"
        }
      }
    }
    stage('get deploy list') {
      // use k8s-deploy-env docker agent - so we do not need to install kubectl
      agent {
        docker {
          image "docker.dbc.dk/k8s-deploy-env:latest"
          alwaysPull true
          label "master"
        }
      }

      steps {
        script {
          withCredentials([file(credentialsId: 'kubecert-frontend', variable: 'KUBECONFIG')]) {
//            dir('jenkins/janitor') {
//              sh """
//              cp ${KUBECONFIG} fisk.txt
//              """
//            }
            DEPLOYS = sh(returnStdout: true, script: "kubectl -n $NAMESPACE --kubeconfig '${KUBECONFIG}' get deployments -o yaml").trim()
            writeYaml file:"deploys.yml", data:DEPLOYS
          }
          stash name: "deploys", includes: "deploys.yml"
        }


      }
    }
    stage('get repo list') {
      agent {
        node { label 'master' }
      }
      steps {
        unstash "deploys"
        script {

            def fisk = readYaml file: "deploys.yml"
            dir('jenkins/janitor') {
              unstash "kube-config"
              sh """
            virtualenv --system-site-packages venv
            . venv/bin/activate
            pip install kubernetes
            
            python fetch_git_branches.py -u https://github.com/DBCDK/bibdk
          """
              //print(fisk)
            }

        }
//        checkout scm
//        script {
//          dir('jenkins/janitor') {
//            GITREPOS = sh(returnStdout: true, script: "./parse_git_repos.sh".trim())
//            def hest = GITREPOS.split(' ')
//            for (String item : hest) {
//              print("FISK")
//              println item
//            }
//          }
//        }
      }
    }
  }
}
