#! groovy
def NAMESPACE = 'frontend-features'
def DEPLOYS
def GITREPOS

pipeline {
  agent {
    node { label 'devel8' }
  }
  options {
    buildDiscarder(logRotator(artifactDaysToKeepStr: "", artifactNumToKeepStr: "", daysToKeepStr: "", numToKeepStr: "5"))
    timestamps()
    gitLabConnection('gitlab.dbc.dk')
    // Limit concurrent builds to one pr. branch.
    disableConcurrentBuilds()
  }
  stages {
    stage('get config'){
      agent {
        node { label 'devel8' }
      }
      steps{
        dir('bibdk_config'){
          git branch: 'develop',
            credentialsId: 'dscrum_ssh_gitlab',
            url: 'gitlab@gitlab.dbc.dk:d-scrum/d7/bibliotek-dk/bibdk_config.git'
        }
        dir('bibdk_config/jenkins'){
          stash name: "kube-config", includes: "kubeconfig.yaml"
        }
      }
    }

    stage('get repo list') {
      agent {
        node { label 'devel8' }
      }
      steps {
        script {
            dir('jenkins/janitor') {
              unstash "kube-config"
              sh """
            virtualenv --system-site-packages venv
            . venv/bin/activate
            pip install kubernetes
            
            python fetch_git_branches.py -u https://github.com/DBCDK/bibdk
            """
            }
        }
//        checkout scm
//        script {
//          dir('jenkins/janitor') {
//            GITREPOS = sh(returnStdout: true, script: "./parse_git_repos.sh".trim())
//            def hest = GITREPOS.split(' ')
//            for (String item : hest) {
//              print("FISK")
//              println item
//            }
//          }
//        }
      }
    }
    stage('clean up') {
      // use k8s-deploy-env docker agent - so we do not need to install kubectl
      agent {
        docker {
          image "docker.dbc.dk/k8s-deploy-env:latest"
          alwaysPull true
          label "devel8"
        }
      }
      steps {
        dir('jenkins/janitor') {
          script {
            def configmapbase = 'bibliotekdk-config-'
            def file = readFile("delete_me.txt")
            def repos = file.split(' ')
            for (String item : repos) {
              sh """
                        kubectl -n $NAMESPACE --kubeconfig '${KUBECONFIG}' delete deployment $item
                        kubectl -n $NAMESPACE --kubeconfig '${KUBECONFIG}' delete configmap $configmapbase + $item
              """

              print("FISK")
              println item
            }
          }
        }
      }
    }
    // @TODO delete workspace
  }
}
